[package]
name = "instr_search"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
rustc-hash = "2.1.0"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "instr_search"
harness = false
